version: '3'

services:
  nginx:
      build:
        context: ./nginx
      volumes:
        - ../src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/conf.d/:/etc/nginx/conf.d
      depends_on:
        - php-fpm
      ports:
        - "80:80"
        - "443:443"
  php-fpm:
      build:
        context: ./php-fpm
      volumes:
        - ../src:/var/www
  db:
      image: postgres:12
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRES_DB: laravel
      volumes:
        - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
  adminer:
      image: adminer
      restart: always
      ports:
        - 8082:8080
  composer:
      image: composer/composer
      volumes:
        - ../src:/var/www
      working_dir: /var/www
      environment:
        COMPOSER_MEMORY_LIMIT: -1
