version: '3'

services:
  nginx:
      build:
        context: ./nginx
      volumes:
        - ../src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/conf.d/:/etc/nginx/conf.d
      depends_on:
        - php-fpm
        - db
      ports:
        - "80:80"
        - "443:443"
  php-fpm:
      build:
        context: ./php-fpm
      volumes:
        - ../src:/var/www
  db:
      image: mysql:5.7.22
      working_dir: /var/www/app
      volumes:
        - ../.persist/.mysqldata:/var/lib/mysql
        - ./docker/mysql:/etc/mysql/conf.d
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret
  adminer:
      image: adminer
      restart: always
      ports:
        - 8082:8080
  composer:
      image: composer/composer
      volumes:
        - ../src:/var/www
      working_dir: /var/www
      environment:
        COMPOSER_MEMORY_LIMIT: -1